### PR TITLE
Add regex support to line in order to remove not diffable content like pointer addresses

### PR DESCRIPTION
**Pull request by mackoj**

### CODE REVIEW

**Comment by stephencelis** [comment]
Hi @mackoj! Thanks for the PR and sorry for the delay! WWDC and travel and such :) @mbrandonw and I have a few ideas on how to make `Diffing` and `Snapshotting` a bit more easily extensible. We want sketch it out a bit when we can and see if it helps this use case (and others) more generally.

**Comment by mackoj** [comment]
@stephencelis did you get time to work on how to better ways to extend `Diffing` and `Snapshotting` ?

**Comment by stephencelis** [comment]
@mackoj Not yet! 😅 Now that TCA is out @mbrandonw and I should spend some time on a bug bash for snapshot-testing. There are a bunch of outstanding things we'd like to unblock. We'll be chatting about it tomorrow.

**Comment by mackoj** [comment]
🤷‍♂️

**Pull request closed without merging**
