### PR TITLE
Add iPhone 13 devices

### LINKED ISSUE #594: Latest iOS device resolutions are missing
**The issue**
The `ViewImageConfig` struct should include static functions for all the latest devices.

I checked `main`, and they're not there either. (Note that struct is defined in a file named `View.swift` for some reason.)

**Environment**
  - swift-snapshot-testing version [e.g. 1.9.0]
  - Xcode [e.g. 13.3] (but it doesn't matter)

**Workaround**
I added the following extension in my project, but I only need portrait, not landscape, so I didn't test for those safe area values. I would probably have created a PR, but there are already so many. I figured maybe this would help someone else looking for these.

```Swift
extension ViewImageConfig {

    public static let iPhone13 = ViewImageConfig.iPhone13(.portrait)

    public static func iPhone13(_ orientation: Orientation) -> ViewImageConfig {
        let safeArea: UIEdgeInsets
        let size: CGSize
        switch orientation {
        case .landscape:
            // warning: unverified (unused) values
            safeArea = .init(top: 0, left: 44, bottom: 24, right: 44)
            size = .init(width: 844, height: 390)
        case .portrait:
            safeArea = .init(top: 47, left: 0, bottom: 34, right: 0)
            size = .init(width: 390, height: 844)
        }
        return .init(safeArea: safeArea, size: size, traits: .iPhoneX(orientation))
    }

    public static let iPhone13Mini = ViewImageConfig.iPhone13Mini(.portrait)

    public static func iPhone13Mini(_ orientation: Orientation) -> ViewImageConfig {
        let safeArea: UIEdgeInsets
        let size: CGSize
        switch orientation {
        case .landscape:
            // warning: unverified (unused) values
            safeArea = .init(top: 0, left: 44, bottom: 24, right: 44)
            size = .init(width: 812, height: 375)
        case .portrait:
            safeArea = .init(top: 50, left: 0, bottom: 34, right: 0)
            size = .init(width: 375, height: 812)
        }
        return .init(safeArea: safeArea, size: size, traits: .iPhoneX(orientation))
    }

    /// This is the same as the `iPhone13`
    public static let iPhone13Pro = ViewImageConfig.iPhone13(.portrait)

    public static let iPhone13ProMax = ViewImageConfig.iPhone13ProMax(.portrait)

    public static func iPhone13ProMax(_ orientation: Orientation) -> ViewImageConfig {
        let safeArea: UIEdgeInsets
        let size: CGSize
        switch orientation {
        case .landscape:
            // warning: unverified (unused) values
            safeArea = .init(top: 0, left: 44, bottom: 24, right: 44)
            size = .init(width: 926, height: 428)
        case .portrait:
            safeArea = .init(top: 47, left: 0, bottom: 34, right: 0)
            size = .init(width: 428, height: 926)
        }
        return .init(safeArea: safeArea, size: size, traits: .iPhoneX(orientation))
    }

    public static let iPhoneSe3rdGen = ViewImageConfig.iPhoneSe3rdGen(.portrait)

    public static func iPhoneSe3rdGen(_ orientation: Orientation = .portrait) -> ViewImageConfig {
        let safeArea: UIEdgeInsets
        let size: CGSize
        switch orientation {
        case .landscape:
            safeArea = .zero
            size = .init(width: 667, height: 375)
        case .portrait:
            safeArea = .init(top: 20, left: 0, bottom: 0, right: 0)
            size = .init(width: 375, height: 667)
        }
        return .init(safeArea: safeArea, size: size, traits: .iPhoneSe(orientation))
    }

}

```

### PR DESCRIPTION
**Pull request by luispadron**
Closes #594

This PR adds the `iPhone13`, `iPhone13Pro` and `iPhone13ProMax` devices for snapshot testing and adds a missing `iPhone12Pro` configuration.

I took the numbers for device config from: https://useyourloaf.com/blog/iphone-13-screen-sizes

I believe the traits should be the same as iPhone 12

### CODE REVIEW

**Review by ylem — APPROVED** [review]
I can confirm all added screen size values based on [useyourloaf](https://useyourloaf.com/blog/iphone-13-screen-sizes) are correct.

**Comment by luispadron** [comment]
Thanks for confirming! Now, just need a review from a maintainer (:

**Comment by djpearce** [comment]
Any chance this gets in soon?

**Comment by armanarutiunov** [comment]
Thanks for this PR @luispadron! Before maintainers approve this, is there a chance you also squeeze in the iPhone 14 line up? Thanks!

**Review by stephencelis — APPROVED** [review]

**Comment by luispadron** [comment]
@armanarutiunov Looks like I didn't see the comment in time sorry about that! Id make a new PR to review those separately

**Pull request merged**
