### PR TITLE
Add AccessibilitySnapshotPointfree Plugin

### PR DESCRIPTION
**Pull request by Sherlouk**
Created a hopefully helpful extension to AccessibilitySnapshot, so a quick README update to add it to the list!

### CODE REVIEW

**Comment by stephencelis** [comment]
@Sherlouk Thanks for the PR! We saw Square's project and it's definitely very cool! We have a few thoughts and were wondering what you think.

- Under the hood, doesn't Square's project use (and depend on) iOSSnapshotTestCase? I wonder if there's a way to work with them to decouple this, since bringing your wrapper into a project would automatically bring in two different snapshot testing frameworks, which might be surprising 😅 If that's not possible, maybe we should add a caveat/warning to let folks know, both in your project's README and in our README where we would link to it?

- What do you think of naming the project "AccessibilitySnapshotTesting" instead of "AccessibilitySnapshotPointfree"?

**Comment by Sherlouk** [comment]
Thanks for the response @stephencelis 

On the first point there - I've been working with the people over there to address this and we've actually worked together to break the iOSSnapshotTestCase dependency out into an optional subspec. My project only depends on their "Core" framework and therefore has no dependency on the Uber library.

On the second point, the naming was difficult - I had thought of "AccessibilitySnapshotTesting" but I didn't think it was immediately clear that it was relating to this tool and wasn't "different enough" to the CashApp library "AccessibilitySnapshot".

**Comment by Sherlouk** [comment]
https://github.com/cashapp/AccessibilitySnapshot/issues/3 was the discussion, if you're interested.

**Comment by stephencelis** [comment]
Oh very nice! Maybe on naming the pod we could use the category naming mentality of "AccessibilitySnapshot+SnapshotTesting"?

One other bummer is that AccessibilitySnapshot isn't SPM-compatible, do you can't provide an SPM module :( Maybe they'll address that in the future, but looks like they're still very Objective-C-heavy.

**Comment by Sherlouk** [comment]
They're keen to adopt SPM support - one of their dependencies however does not which is the current blocker. Soon as they support it, I'll support it - though this is purely an optional add-on so I don't think that's a huge concern here!

I'll rename it to that, solid idea 👍

**Comment by Sherlouk** [comment]
Just working on publishing the pod but should all be good 👍

**Comment by Sherlouk** [comment]
Thanks for the recommendation there Stephen, think it's a much better name 👍 

and thanks for the merge, there's been a handful of people who have asked for this extension so that's props to good work over here!

**Comment by mbrandonw** [comment]
This is really awesome @Sherlouk! Thanks for taking care of it and pushing for the necessary changes to `AccessibilitySnapshot` to make it a possibility!

**Pull request merged**
