### PR TITLE
(chore): Add podspec

### PR DESCRIPTION
**Pull request by zhmul**
This PR adds a `.podspec` file to add support for CocoaPods.

### CODE REVIEW

**Comment by ninjazoete** [comment]
Why was this closed? Anyone? 
I have really old version of the framework and don't want to jump to SPM on this old project. I would really need cocoapods support.

**Comment by stephencelis** [comment]
@ninjazoete We sunset CocoaPods support many versions ago. See this discussion and related links for more: https://github.com/pointfreeco/swift-snapshot-testing/discussions/754

You don't have to jump to SPM, but you do have to maintain your own pod spec if you want a more recent version.

**Comment by ninjazoete** [comment]
@stephencelis do you guys have a binary distributed somewhere? I am trying to build it but it has exact errors described here: 
https://github.com/pointfreeco/swift-snapshot-testing/issues/536

**Comment by stephencelis** [comment]
@ninjazoete We do not distribute a binary. That thread does appear to have a solution described: enabling test paths. Did you try that?

**Comment by ninjazoete** [comment]
@stephencelis I tried but when I want to use swift create-xcframework I get:
`debug: evaluating manifest for 'swift-snapshot-testing-1.15.2' v. unknown 
error: missingKey("product_type")
debug: evaluating manifest for 'swift-snapshot-testing-1.15.2' v. unknown 
error: missingKey("product_type")
Error: fatalError`

When I do the xcodebuild approach I get these XCTest problems.

**Comment by ninjazoete** [comment]
Ok I found that all these problems are related to other things.
swift create-xcframework problem is https://github.com/unsignedapps/swift-create-xcframework/pull/93
and the missing XCTest type is problem with swift itself.. we all love apple :)

**Pull request closed without merging**
