### PR TITLE
Xcode project for Carthage compatibility

### LINKED ISSUE #39: Carthage compatibility / Xcode project
Hi! 👋 

Would you accept a PR to add an `.xcodeproj`, making this library Carthage compatible?

### PR DESCRIPTION
**Pull request by mdiep**
Resolves #39.

I didn't add anything to the makefile to generate the Xcode project because the generated Xcode project isn't really suitable for distributing. (It's not composed well, missing required build settings, etc.)

Some iOS tests fail on my machine, but I think that's a function of which simulator you're using.

### CODE REVIEW

**Comment by stephencelis** [comment]
Nice!

> I didn't add anything to the makefile to generate the Xcode project because the generated Xcode project isn't really suitable for distributing. (It's not composed well, missing required build settings, etc.)

Ah, is this hand-rolled then? Is it possible to get in a shape where we can use `swift package generate-xcodeproj` with the `--xcconfig-overrides` option? _E.g._:

https://github.com/pointfreeco/swift-web/blob/dc1c5b700f698a16f7c736ea0f7d7bdc2e5d3d37/Makefile#L14

Or is there still some config that can't be done this way?

**Comment by mdiep** [comment]
The generated project is set up to generate 3 frameworks:

- `Diff.framework`
- `WKSnapshotConfigurationShim.framework`
- `SnapshotTesting.framework`

I'm also not sure how multiple platforms work on the generated project.

The pain of having 3 frameworks makes it worth manually maintaining this IMO, but if you want it to be generated, I'll do it. ☺️

**Comment by stephencelis** [comment]
Thoughts, @mbrandonw? Our workflow right now is a liberal sprinkling of `swift package generate-xcodeproj`, so wondering how this would change things.

**Comment by mdiep** [comment]
_bump_

**Comment by mbrandonw** [comment]
Hey! I'm a lil torn on this one. Considering our flow of working on this project, it is very likely we will accidentally blow away the xcodeproj changes on accident and break it for everyone.

But also, at the same time, we haven't made an official 0.1.0 release yet, so anyone using this is walking into a minefield already.

So, I guess let's merge and try it out!

Thanks @mdiep!

**Pull request merged**
