### PR TITLE
Compare image contexts in same colorspace

### PR DESCRIPTION
**Pull request by dflems**
I ran some of our snapshots through a lossless image optimizer (ImageOptim) and it made a lot of them significantly smaller (removing unnecessary alpha channel, converting to monochrome or 8-bit color, etc). Unfortunately, after this conversion, image comparison failed in `swift-snapshot-testing`. I think this is because the contexts were compared against one-another using different color spaces.

This PR converts both the snapshot and the reference to the same colorspace when comparing bytes: SRGB with alpha channel. I don't know if this is the best or the most efficient but it seemed consistent enough and worked against our 1,600 snapshot tests. If anyone has some better suggestions, I'm open to hearing them (generally unfamiliar with this kind of stuff)

### CODE REVIEW

**Comment by dflems** [comment]
@stephencelis

**Comment by dflems** [comment]
@stephencelis :wave:

**Comment by dflems** [comment]
@stephencelis :wave: again

**Comment by dflems** [comment]
@stephencelis ready to give up on this PR... any feedback?

**Review by stephencelis — APPROVED** [review]
Ha sorry about the delay! We have a lot of projects in-flight but this one has had the stablest API, so it's gotten a little less attention. We reviewed it this morning and it looks good to merge!

**Pull request merged**
