### PR TITLE
NSView image snapshot

### PR DESCRIPTION
**Pull request by schwmi**
Using the project for snapshotting some screens of our Mac app delivered bad results, especially for capturing layer properties (like background color, shadows, roundedCorners …). Changing the capturing method resolved the issue for us.

## Changes

- Change method for generating NSImage out of NSView.
- Update NSView snapshot tests to work on Catalina + to work with the new snapshot generating method.
- Add an unit test showing the problematic behavior when used with the previous snapshotting logic.

### CODE REVIEW

**Comment by schwmi** [comment]
After having this open for 2 months with no reaction at all it seems there is no interest from the maintainers in improving this project.

**Comment by stephencelis** [comment]
Sorry about the delay, @schwmi! The two of us have been pretty swamped the past few months and haven't had as much free time to devote to this. We'd love to have members of the community available to keep things like this on the right track. Would you like to be added as a contributor to help move things like this forward? No pressure either way!

**Comment by schwmi** [comment]
Thanks for the feedback - I‘ll have a look at these conflicts this week so that we can merge the changes in 👍

**Comment by schwmi** [comment]
I had to update 5 reference files for the macOS tests - you can see old/new comparison in the attached folder.

[Reference file changes.zip](https://github.com/pointfreeco/swift-snapshot-testing/files/3946839/Reference.file.changes.zip)

**Comment by stephencelis** [comment]
Perfect! Thanks so much!

**Pull request merged**
