### PR TITLE
Fix false positive when asserting reference image with empty image

### PR DESCRIPTION
**Pull request by nuno-vieira**
Hello 👋 

### Bug Description
Unfortunately in the project that I'm working on, we encountered some false positives, where we thought that the tests were actually working, but they were not. What happened was that after some refactorings, some of the tests passed, but actually, the new reference images were the red empty image and the framework assumed that everything was okay.

In order to unit test this, I previously recorded a snapshot with content, and then verify against an empty view and check that it fails. 

Fixes: https://github.com/pointfreeco/swift-snapshot-testing/issues/454, a duplicate of https://github.com/pointfreeco/swift-snapshot-testing/issues/414

### CODE REVIEW

**Comment by nuno-vieira** [comment]
@mbrandonw @stephencelis Any update on this, please? 🙏

**Comment by Fab1n** [comment]
@mbrandonw @stephencelis Any update on this, please?

**Review by Fab1n — APPROVED** [review]
This looks very good in my eyes. Any concerns from the authors?

**Review by Fab1n — APPROVED** [review]
Now I got the review right

**Review by gabrielmoraees — APPROVED** [review]

**Review by stephencelis — APPROVED** [review]
Thanks!

**Pull request merged**
