### PR TITLE
Add iPhone 12 and iPhone 12 Pro Max configs

### LINKED ISSUE #416: Add support for iPhone 12 Pro Max

### PR DESCRIPTION
**Pull request by imvm**
Resolves #416.
I can also add the iPhone 12 mini, which has a different screen scale (3x) but the same screen size as the iPhone X.

### CODE REVIEW

**Review by stephencelis — APPROVED** [review]
Thanks!

**Comment by stephencelis** [comment]
> I can also add the iPhone 12 mini, which has a different screen scale (3x) but the same screen size as the iPhone X.

We're open to this, but feel free to do a separate PR 😄

**Comment by DanielKrofchick** [comment]
The latest release [`1.9.0`](https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.9.0) was put out on Apr 27 2021. Useful additions have been added since then, like this one on Aug 16 2021. Considering it's been 9 months since the last release, is there any plan to release a new version or should we be pulling from `main`?

**Comment by DanielKrofchick** [comment]
@stephencelis with respect to my above comment, are there any plans to release new versions?

**Pull request merged**
